/* eslint-disable max-len */
export default (client, handler) => ({
  /** @param {{query?:{page:string,per_page:string,order_by:string,sort:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:string,message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:string,target_path:string,broadcast_type:string,dismissable:string,active:string}}>} */
  get: ({query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/broadcast_messages',headers:{Accept:'application/json'},variable:[],query:[{name:'page',type:'string'},{name:'per_page',type:'string'},{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, {query}, options]),
  /** @param {{data:{message:string,starts_at:{},ends_at:{},color:string,font:string,target_access_levels:[number,number],target_path:string,broadcast_type:{},dismissable:boolean}}} request @param {any} [options={}] @return {Promise<{code:201,data:{id:string,message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:string,target_path:string,broadcast_type:string,dismissable:string,active:string}}>} */
  post: ({data} = {}, options = {}) => handler.apply({method:'post',url:'api/v4/broadcast_messages',headers:{'Content-Type':'application/json',Accept:'application/json'},variable:[],data:{mode:'raw',raw:{message:'string',starts_at:{},ends_at:{},color:'string',font:'string',target_access_levels:['number','number'],target_path:'string',broadcast_type:{},dismissable:'boolean'},options:{raw:{language:'json'}}}}, [client, {data}, options]),
  /** @param {{params:{id:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:string,message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:string,target_path:string,broadcast_type:string,dismissable:string,active:string}}>} */
  getOne: ({params} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/broadcast_messages/:id',headers:{Accept:'application/json'},variable:[{name:'id',type:'string'}]}, [client, { params}, options]),
  /** @param {{params:{id:string},data:{message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:[number,number],target_path:string,broadcast_type:string,dismissable:boolean}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:string,message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:string,target_path:string,broadcast_type:string,dismissable:string,active:string}}>} */
  put: ({params,data} = {}, options = {}) => handler.apply({method:'put',url:'api/v4/broadcast_messages/:id',headers:{'Content-Type':'application/json',Accept:'application/json'},variable:[{name:'id',type:'string'}],data:{mode:'raw',raw:{message:'string',starts_at:'string',ends_at:'string',color:'string',font:'string',target_access_levels:['number','number'],target_path:'string',broadcast_type:'string',dismissable:'boolean'},options:{raw:{language:'json'}}}}, [client, { params, data}, options]),
  /** @param {{params:{id:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:string,message:string,starts_at:string,ends_at:string,color:string,font:string,target_access_levels:string,target_path:string,broadcast_type:string,dismissable:string,active:string}}>} */
  delete: ({params} = {}, options = {}) => handler.apply({method:'delete',url:'api/v4/broadcast_messages/:id',headers:{Accept:'application/json'},variable:[{name:'id',type:'string'}]}, [client, { params}, options])
});