/* eslint-disable max-len */
export default (client, handler) => ({
  /** @param {{data:{configuration[url]:string,configuration[access_token]:string,entities[source_type]:string,entities[source_full_path]:string,entities[destination_namespace]:string,entities[destination_slug]:string,entities[destination_name]:string,entities[migrate_projects]:true}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:number,status:string,source_type:string,created_at:string,upstringd_at:string,has_failures:boolean}}|{code:400}|{code:401}|{code:404}|{code:422}|{code:503}>} */
  post: ({data} = {}, options = {}) => handler.apply({method:'post',url:'api/v4/bulk_imports',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},variable:[],data:{mode:'urlencoded',urlencoded:{'configuration[url]':'string','configuration[access_token]':'string','entities[source_type]':'string','entities[source_full_path]':'string','entities[destination_namespace]':'string','entities[destination_slug]':'string','entities[destination_name]':'string','entities[migrate_projects]':'true'}}}, [client, {data}, options]),
  /** @param {{query?:{page:string,per_page:string,sort:string,status:string,order_by:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:[{id:number,status:string,source_type:string,created_at:string,upstringd_at:string,has_failures:boolean},{id:number,status:string,source_type:string,created_at:string,upstringd_at:string,has_failures:boolean}]}|{code:401}|{code:404}|{code:503}>} */
  get: ({query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/bulk_imports',headers:{Accept:'application/json'},variable:[],query:[{name:'page',type:'string'},{name:'per_page',type:'string'},{name:'sort',type:'string'},{name:'status',type:'string'},{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, {query}, options]),
  "entities": {
    /** @param {{params:{import_id:string},query?:{status:string,page:string,per_page:string,order_by:string,sort:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:[{id:number,bulk_import_id:number,status:string,entity_type:string,source_full_path:string,destination_full_path:string,destination_name:string,destination_slug:string,destination_namespace:string,parent_id:number,namespace_id:number,project_id:number,created_at:string,upstringd_at:string,failures:[{value:{}},{value:{}}],migrate_projects:boolean,has_failures:boolean,stats:object},{id:number,bulk_import_id:number,status:string,entity_type:string,source_full_path:string,destination_full_path:string,destination_name:string,destination_slug:string,destination_namespace:string,parent_id:number,namespace_id:number,project_id:number,created_at:string,upstringd_at:string,failures:[{value:{}},{value:{}}],migrate_projects:boolean,has_failures:boolean,stats:object}]}|{code:401}|{code:404}|{code:503}>} */
    get: ({params,query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/bulk_imports/:import_id/entities',headers:{Accept:'application/json'},variable:[{name:'import_id',type:'string'}],query:[{name:'status',type:'string'},{name:'page',type:'string'},{name:'per_page',type:'string'},{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, { params, query}, options]),
    /** @param {{params:{import_id:string,entity_id:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:number,bulk_import_id:number,status:string,entity_type:string,source_full_path:string,destination_full_path:string,destination_name:string,destination_slug:string,destination_namespace:string,parent_id:number,namespace_id:number,project_id:number,created_at:string,upstringd_at:string,failures:[{relation:string,exception_message:string,exception_class:string,correlation_id_value:string,source_url:string,source_title:string},{relation:string,exception_message:string,exception_class:string,correlation_id_value:string,source_url:string,source_title:string}],migrate_projects:boolean,has_failures:boolean,stats:object}}|{code:401}|{code:404}|{code:503}>} */
    getOne: ({params} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/bulk_imports/:import_id/entities/:entity_id',headers:{Accept:'application/json'},variable:[{name:'import_id',type:'string'},{name:'entity_id',type:'string'}]}, [client, { params}, options]),
    "failures": {
      /** @param {{params:{import_id:string,entity_id:string},query?:{order_by:string,sort:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{relation:string,exception_message:string,exception_class:string,correlation_id_value:string,source_url:string,source_title:string}}|{code:401}|{code:404}|{code:503}>} */
      get: ({params,query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/bulk_imports/:import_id/entities/:entity_id/failures',headers:{Accept:'application/json'},variable:[{name:'import_id',type:'string'},{name:'entity_id',type:'string'}],query:[{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, { params, query}, options])
    }
  },
  /** @param {{params:{import_id:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:number,status:string,source_type:string,created_at:string,upstringd_at:string,has_failures:boolean}}|{code:401}|{code:404}|{code:503}>} */
  getOne: ({params} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/bulk_imports/:import_id',headers:{Accept:'application/json'},variable:[{name:'import_id',type:'string'}]}, [client, { params}, options]),
  "cancel": {
    /** @param {{params:{import_id:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:{id:number,status:string,source_type:string,created_at:string,upstringd_at:string,has_failures:boolean}}|{code:401}|{code:403}|{code:404}|{code:503}>} */
    post: ({params} = {}, options = {}) => handler.apply({method:'post',url:'api/v4/bulk_imports/:import_id/cancel',headers:{Accept:'application/json'},variable:[{name:'import_id',type:'string'}]}, [client, { params}, options])
  }
});