/* eslint-disable max-len */
export default (client, handler) => ({
  /** @param {{query?:{order_by:string,sort:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:[{name:string,state:string,gates:{key:{value:{}},value:{value:{}}},definition:{name:{value:{}},feature_issue_url:{value:{}},introduced_by_url:{value:{}},rollout_issue_url:{value:{}},milestone:{value:{}},log_state_changes:{value:{}},type:{value:{}},group:{value:{}},default_enabled:{value:{}}}},{name:string,state:string,gates:{key:{value:{}},value:{value:{}}},definition:{name:{value:{}},feature_issue_url:{value:{}},introduced_by_url:{value:{}},rollout_issue_url:{value:{}},milestone:{value:{}},log_state_changes:{value:{}},type:{value:{}},group:{value:{}},default_enabled:{value:{}}}}]}>} */
  get: ({query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/features',headers:{Accept:'application/json'},variable:[],query:[{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, {query}, options]),
  "definitions": {
    /** @param {{query?:{order_by:string,sort:string}}} request @param {any} [options={}] @return {Promise<{code:200,data:[{name:string,feature_issue_url:string,introduced_by_url:string,rollout_issue_url:string,milestone:string,log_state_changes:string,type:string,group:string,default_enabled:string},{name:string,feature_issue_url:string,introduced_by_url:string,rollout_issue_url:string,milestone:string,log_state_changes:string,type:string,group:string,default_enabled:string}]}>} */
    get: ({query} = {}, options = {}) => handler.apply({method:'get',url:'api/v4/features/definitions',headers:{Accept:'application/json'},variable:[],query:[{name:'order_by',type:'string'},{name:'sort',type:'string'}]}, [client, {query}, options])
  },
  /** @param {{params:{name:string},data:{value:string,key:string,feature_group:string,user:string,group:string,namespace:string,project:string,repository:string,force:boolean}}} request @param {any} [options={}] @return {Promise<{code:201,data:{name:string,state:string,gates:{key:string,value:number},definition:{name:string,feature_issue_url:string,introduced_by_url:string,rollout_issue_url:string,milestone:string,log_state_changes:string,type:string,group:string,default_enabled:string}}}|{code:400}>} */
  post: ({params,data} = {}, options = {}) => handler.apply({method:'post',url:'api/v4/features/:name',headers:{'Content-Type':'application/json',Accept:'application/json'},variable:[{name:'name',type:'string'}],data:{mode:'raw',raw:{value:'string',key:'string',feature_group:'string',user:'string',group:'string',namespace:'string',project:'string',repository:'string',force:'boolean'},options:{raw:{language:'json'}}}}, [client, { params, data}, options]),
  /** @param {{params:{name:string}}} request @param {any} [options={}] @return {Promise<{code:204}>} */
  delete: ({params} = {}, options = {}) => handler.apply({method:'delete',url:'api/v4/features/:name',variable:[{name:'name',type:'string'}]}, [client, { params}, options])
});