export default (client: any, handler: any) => ({
  /** @param {{params:{hook_id:string},clientOptions:{}}} requestOptions * @return {[{code:204,data:{id:string,url:string,name:string,description:string,created_at:dateTime,push_events:boolean,tag_push_events:boolean,merge_requests_events:boolean,repository_update_events:boolean,enable_ssl_verification:boolean,alert_status:symbol,disabled_until:dateTime,url_variables:[object,object],custom_webhook_template:string}},{code:404}]} */
  get: ({query = {},clientOptions = {}} = {}) => handler.apply({method:"get",url:"api/v4/hooks",resource:"api",variable:[],headers:{Accept:"application/json"},query:[{name:"page",type:"string"},{name:"per_page",type:"string"}],data:null}, [client, {query, clientOptions}]),
  post: ({params = {},clientOptions = {}} = {}) => handler.apply({method:"post",url:"api/v4/hooks/:hook_id",resource:"api",variable:[{name:"hook_id",type:"string"}],headers:{},query:[],data:null}, [client, { params, clientOptions}]),
  getOne: ({params = {},clientOptions = {}} = {}) => handler.apply({method:"get",url:"api/v4/hooks/:hook_id",resource:"api",variable:[{name:"hook_id",type:"string"}],headers:{Accept:"application/json"},query:[],data:null}, [client, { params, clientOptions}]),
  put: ({params = {},data = {},clientOptions = {}} = {}) => handler.apply({method:"put",url:"api/v4/hooks/:hook_id",resource:"api",variable:[{name:"hook_id",type:"string"}],headers:{"Content-Type":"application/json",Accept:"application/json"},query:[],data:{mode:"raw",raw:{url:"string",name:"string",description:"string",token:"string",push_events:"boolean",tag_push_events:"boolean",merge_requests_events:"boolean",repository_update_events:"boolean",enable_ssl_verification:"boolean",url_variables:[{key:"string",value:"string"},{key:"string",value:"string"}]},options:{raw:{language:"json"}}}}, [client, { params, data, clientOptions}]),
  delete: ({params = {},clientOptions = {}} = {}) => handler.apply({method:"delete",url:"api/v4/hooks/:hook_id",resource:"api",variable:[{name:"hook_id",type:"string"}],headers:{Accept:"application/json"},query:[],data:null}, [client, { params, clientOptions}]),
  url_variables: {
    /** @param {{params:{hook_id:string,key:string},clientOptions:{}}} requestOptions * @return {[{code:204}]} */
    put: ({params = {},data = {},clientOptions = {}} = {}) => handler.apply({method:"put",url:"api/v4/hooks/:hook_id/url_variables/:key",resource:"v4",variable:[{name:"hook_id",type:"string"},{name:"key",type:"string"}],headers:{"Content-Type":"application/json"},query:[],data:{mode:"raw",raw:{value:"string"},options:{raw:{language:"json"}}}}, [client, { params, data, clientOptions}]),
    delete: ({params = {},clientOptions = {}} = {}) => handler.apply({method:"delete",url:"api/v4/hooks/:hook_id/url_variables/:key",resource:"v4",variable:[{name:"hook_id",type:"string"},{name:"key",type:"string"}],headers:{},query:[],data:null}, [client, { params, clientOptions}])
  }
})